/* JS */ gapi.loaded_0(function(_){var window=this;
/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var ma,oa,xa,Ba,Da,Ea,La,Sa;_.ja=function(a){return function(){return _.ea[a].apply(this,arguments)}};_._DumpException=function(a){throw a;};_.ea=[];ma=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};oa="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
xa=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("a");};Ba=xa(this);Da=function(a,b){if(b)a:{var c=Ba;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&oa(c,a,{configurable:!0,writable:!0,value:b})}};
Da("Symbol",function(a){if(a)return a;var b=function(e,f){this.pO=e;oa(this,"description",{configurable:!0,writable:!0,value:f})};b.prototype.toString=function(){return this.pO};var c=0,d=function(e){if(this instanceof d)throw new TypeError("Symbol is not a constructor");return new b("jscomp_symbol_"+(e||"")+"_"+c++,e)};return d});
Da("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=Ba[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&oa(d.prototype,a,{configurable:!0,writable:!0,value:function(){return Ea(ma(this))}})}return a});Ea=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a};
_.Ha=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:ma(a)}};_.Ja="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b};if("function"==typeof Object.setPrototypeOf)La=Object.setPrototypeOf;else{var Ma;a:{var Na={a:!0},Pa={};try{Pa.__proto__=Na;Ma=Pa.a;break a}catch(a){}Ma=!1}La=Ma?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}
_.Ra=La;Sa=function(a,b,c){if(null==a)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""};Da("String.prototype.startsWith",function(a){return a?a:function(b,c){var d=Sa(this,b,"startsWith"),e=d.length,f=b.length;c=Math.max(0,Math.min(c|0,d.length));for(var g=0;g<f&&c<e;)if(d[c++]!=b[g++])return!1;return g>=f}});
var Ta=function(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var f=c++;return{value:b(f,a[f]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e};Da("Array.prototype.keys",function(a){return a?a:function(){return Ta(this,function(b){return b})}});Da("Array.prototype.values",function(a){return a?a:function(){return Ta(this,function(b,c){return c})}});
var Ua=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};Da("Object.values",function(a){return a?a:function(b){var c=[],d;for(d in b)Ua(b,d)&&c.push(b[d]);return c}});
Da("Array.from",function(a){return a?a:function(b,c,d){c=null!=c?c:function(k){return k};var e=[],f="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];if("function"==typeof f){b=f.call(b);for(var g=0;!(f=b.next()).done;)e.push(c.call(d,f.value,g++))}else for(f=b.length,g=0;g<f;g++)e.push(c.call(d,b[g],g));return e}});Da("Object.is",function(a){return a?a:function(b,c){return b===c?0!==b||1/b===1/c:b!==b&&c!==c}});
Da("Array.prototype.includes",function(a){return a?a:function(b,c){var d=this;d instanceof String&&(d=String(d));var e=d.length;c=c||0;for(0>c&&(c=Math.max(c+e,0));c<e;c++){var f=d[c];if(f===b||Object.is(f,b))return!0}return!1}});Da("String.prototype.includes",function(a){return a?a:function(b,c){return-1!==Sa(this,b,"includes").indexOf(b,c||0)}});Da("Object.entries",function(a){return a?a:function(b){var c=[],d;for(d in b)Ua(b,d)&&c.push([d,b[d]]);return c}});
var Va="function"==typeof Object.assign?Object.assign:function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(d)for(var e in d)Ua(d,e)&&(a[e]=d[e])}return a};Da("Object.assign",function(a){return a||Va});Da("Array.prototype.flat",function(a){return a?a:function(b){b=void 0===b?1:b;for(var c=[],d=0;d<this.length;d++){var e=this[d];Array.isArray(e)&&0<b?(e=Array.prototype.flat.call(e,b-1),c.push.apply(c,e)):c.push(e)}return c}});
Da("Array.prototype.entries",function(a){return a?a:function(){return Ta(this,function(b,c){return[b,c]})}});
Da("WeakMap",function(a){function b(){}function c(l){var m=typeof l;return"object"===m&&null!==l||"function"===m}function d(l){if(!Ua(l,f)){var m=new b;oa(l,f,{value:m})}}function e(l){var m=Object[l];m&&(Object[l]=function(n){if(n instanceof b)return n;Object.isExtensible(n)&&d(n);return m(n)})}if(function(){if(!a||!Object.seal)return!1;try{var l=Object.seal({}),m=Object.seal({}),n=new a([[l,2],[m,3]]);if(2!=n.get(l)||3!=n.get(m))return!1;n.delete(l);n.set(m,4);return!n.has(l)&&4==n.get(m)}catch(p){return!1}}())return a;
var f="$jscomp_hidden_"+Math.random();e("freeze");e("preventExtensions");e("seal");var g=0,k=function(l){this.Ca=(g+=Math.random()+1).toString();if(l){l=_.Ha(l);for(var m;!(m=l.next()).done;)m=m.value,this.set(m[0],m[1])}};k.prototype.set=function(l,m){if(!c(l))throw Error("b");d(l);if(!Ua(l,f))throw Error("c`"+l);l[f][this.Ca]=m;return this};k.prototype.get=function(l){return c(l)&&Ua(l,f)?l[f][this.Ca]:void 0};k.prototype.has=function(l){return c(l)&&Ua(l,f)&&Ua(l[f],this.Ca)};k.prototype.delete=
function(l){return c(l)&&Ua(l,f)&&Ua(l[f],this.Ca)?delete l[f][this.Ca]:!1};return k});
Da("Map",function(a){if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var k=Object.seal({x:4}),l=new a(_.Ha([[k,"s"]]));if("s"!=l.get(k)||1!=l.size||l.get({x:4})||l.set({x:4},"t")!=l||2!=l.size)return!1;var m=l.entries(),n=m.next();if(n.done||n.value[0]!=k||"s"!=n.value[1])return!1;n=m.next();return n.done||4!=n.value[0].x||"t"!=n.value[1]||!m.next().done?!1:!0}catch(p){return!1}}())return a;var b=new WeakMap,c=function(k){this.yf={};this.Ze=
f();this.size=0;if(k){k=_.Ha(k);for(var l;!(l=k.next()).done;)l=l.value,this.set(l[0],l[1])}};c.prototype.set=function(k,l){k=0===k?0:k;var m=d(this,k);m.list||(m.list=this.yf[m.id]=[]);m.we?m.we.value=l:(m.we={next:this.Ze,ej:this.Ze.ej,head:this.Ze,key:k,value:l},m.list.push(m.we),this.Ze.ej.next=m.we,this.Ze.ej=m.we,this.size++);return this};c.prototype.delete=function(k){k=d(this,k);return k.we&&k.list?(k.list.splice(k.index,1),k.list.length||delete this.yf[k.id],k.we.ej.next=k.we.next,k.we.next.ej=
k.we.ej,k.we.head=null,this.size--,!0):!1};c.prototype.clear=function(){this.yf={};this.Ze=this.Ze.ej=f();this.size=0};c.prototype.has=function(k){return!!d(this,k).we};c.prototype.get=function(k){return(k=d(this,k).we)&&k.value};c.prototype.entries=function(){return e(this,function(k){return[k.key,k.value]})};c.prototype.keys=function(){return e(this,function(k){return k.key})};c.prototype.values=function(){return e(this,function(k){return k.value})};c.prototype.forEach=function(k,l){for(var m=this.entries(),
n;!(n=m.next()).done;)n=n.value,k.call(l,n[1],n[0],this)};c.prototype[Symbol.iterator]=c.prototype.entries;var d=function(k,l){var m=l&&typeof l;"object"==m||"function"==m?b.has(l)?m=b.get(l):(m=""+ ++g,b.set(l,m)):m="p_"+l;var n=k.yf[m];if(n&&Ua(k.yf,m))for(k=0;k<n.length;k++){var p=n[k];if(l!==l&&p.key!==p.key||l===p.key)return{id:m,list:n,index:k,we:p}}return{id:m,list:n,index:-1,we:void 0}},e=function(k,l){var m=k.Ze;return Ea(function(){if(m){for(;m.head!=k.Ze;)m=m.ej;for(;m.next!=m.head;)return m=
m.next,{done:!1,value:l(m)};m=null}return{done:!0,value:void 0}})},f=function(){var k={};return k.ej=k.next=k.head=k},g=0;return c});
Da("Set",function(a){if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var c=Object.seal({x:4}),d=new a(_.Ha([c]));if(!d.has(c)||1!=d.size||d.add(c)!=d||1!=d.size||d.add({x:4})!=d||2!=d.size)return!1;var e=d.entries(),f=e.next();if(f.done||f.value[0]!=c||f.value[1]!=c)return!1;f=e.next();return f.done||f.value[0]==c||4!=f.value[0].x||f.value[1]!=f.value[0]?!1:e.next().done}catch(g){return!1}}())return a;var b=function(c){this.Ha=new Map;if(c){c=
_.Ha(c);for(var d;!(d=c.next()).done;)this.add(d.value)}this.size=this.Ha.size};b.prototype.add=function(c){c=0===c?0:c;this.Ha.set(c,c);this.size=this.Ha.size;return this};b.prototype.delete=function(c){c=this.Ha.delete(c);this.size=this.Ha.size;return c};b.prototype.clear=function(){this.Ha.clear();this.size=0};b.prototype.has=function(c){return this.Ha.has(c)};b.prototype.entries=function(){return this.Ha.entries()};b.prototype.values=function(){return this.Ha.values()};b.prototype.keys=b.prototype.values;
b.prototype[Symbol.iterator]=b.prototype.values;b.prototype.forEach=function(c,d){var e=this;this.Ha.forEach(function(f){return c.call(d,f,f,e)})};return b});_.q={};_.Wa=_.Wa||{};_.A=this||self;_.Ya="closure_uid_"+(1E9*Math.random()>>>0);_.C=function(a,b){a=a.split(".");var c=_.A;a[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||void 0===b?c=c[d]&&c[d]!==Object.prototype[d]?c[d]:c[d]={}:c[d]=b};
_.K=function(a,b){function c(){}c.prototype=b.prototype;a.T=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.yp=function(d,e,f){for(var g=Array(arguments.length-2),k=2;k<arguments.length;k++)g[k-2]=arguments[k];return b.prototype[e].apply(d,g)}};
gadgets=window.gadgets||{};osapi=window.osapi=window.osapi||{};

window.___jsl=window.___jsl||{};
(window.___jsl.cd=window.___jsl.cd||[]).push({gwidget:{parsetags:"explicit"},appsapi:{plus_one_service:"/plus/v1"},csi:{rate:.01},poshare:{hangoutContactPickerServer:"https://plus.google.com"},gappsutil:{required_scopes:["https://www.googleapis.com/auth/plus.me","https://www.googleapis.com/auth/plus.people.recommended"],display_on_page_ready:!1},appsutil:{required_scopes:["https://www.googleapis.com/auth/plus.me","https://www.googleapis.com/auth/plus.people.recommended"],display_on_page_ready:!1},
"oauth-flow":{authUrl:"https://accounts.google.com/o/oauth2/auth",proxyUrl:"https://accounts.google.com/o/oauth2/postmessageRelay",redirectUri:"postmessage"},iframes:{sharebox:{params:{json:"&"},url:":socialhost:/:session_prefix:_/sharebox/dialog"},plus:{url:":socialhost:/:session_prefix:_/widget/render/badge?usegapi=1"},":socialhost:":"https://apis.google.com",":im_socialhost:":"https://plus.googleapis.com",domains_suggest:{url:"https://domains.google.com/suggest/flow"},card:{params:{s:"#",userid:"&"},
url:":socialhost:/:session_prefix:_/hovercard/internalcard"},":signuphost:":"https://plus.google.com",":gplus_url:":"https://plus.google.com",plusone:{url:":socialhost:/:session_prefix:_/+1/fastbutton?usegapi=1"},plus_share:{url:":socialhost:/:session_prefix:_/+1/sharebutton?plusShare=true&usegapi=1"},plus_circle:{url:":socialhost:/:session_prefix:_/widget/plus/circle?usegapi=1"},plus_followers:{url:":socialhost:/_/im/_/widget/render/plus/followers?usegapi=1"},configurator:{url:":socialhost:/:session_prefix:_/plusbuttonconfigurator?usegapi=1"},
appcirclepicker:{url:":socialhost:/:session_prefix:_/widget/render/appcirclepicker"},page:{url:":socialhost:/:session_prefix:_/widget/render/page?usegapi=1"},person:{url:":socialhost:/:session_prefix:_/widget/render/person?usegapi=1"},community:{url:":ctx_socialhost:/:session_prefix::im_prefix:_/widget/render/community?usegapi=1"},follow:{url:":socialhost:/:session_prefix:_/widget/render/follow?usegapi=1"},commentcount:{url:":socialhost:/:session_prefix:_/widget/render/commentcount?usegapi=1"},comments:{url:":socialhost:/:session_prefix:_/widget/render/comments?usegapi=1"},
blogger:{url:":socialhost:/:session_prefix:_/widget/render/blogger?usegapi=1"},youtube:{url:":socialhost:/:session_prefix:_/widget/render/youtube?usegapi=1"},reportabuse:{url:":socialhost:/:session_prefix:_/widget/render/reportabuse?usegapi=1"},additnow:{url:":socialhost:/additnow/additnow.html"},appfinder:{url:"https://gsuite.google.com/:session_prefix:marketplace/appfinder?usegapi=1"},":source:":"1p"},poclient:{update_session:"google.updateSessionCallback"},"googleapis.config":{rpc:"/rpc",root:"https://content.googleapis.com",
"root-1p":"https://clients6.google.com",useGapiForXd3:!0,xd3:"/static/proxy.html",auth:{useInterimAuth:!1}},report:{apis:["iframes\\..*","gadgets\\..*","gapi\\.appcirclepicker\\..*","gapi\\.client\\..*"],rate:1E-4},client:{perApiBatch:!0}});

window.___jsl=window.___jsl||{};(window.___jsl.cd=window.___jsl.cd||[]).push({gwidget:{parsetags:"onload"},iframes:{":source:":"3p"}});

/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var jb,kb,mb;_.$a=function(a,b){return 0<=(0,_.Za)(a,b)};_.bb=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};_.cb=function(){};_.eb=function(a){var b=typeof a;return"object"!=b?b:a?Array.isArray(a)?"array":b:"null"};_.hb=function(a){var b=_.eb(a);return"array"==b||"object"==b&&"number"==typeof a.length};jb=function(a,b,c){return a.call.apply(a.bind,arguments)};
kb=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(b,e)}}return function(){return a.apply(b,arguments)}};_.R=function(a,b,c){_.R=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?jb:kb;return _.R.apply(null,arguments)};_.lb=function(){return Date.now()};mb=function(a){return a};
_.Za=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};
_.nb=Array.prototype.lastIndexOf?function(a,b){return Array.prototype.lastIndexOf.call(a,b,a.length-1)}:function(a,b){var c=a.length-1;0>c&&(c=Math.max(0,a.length+c));if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.lastIndexOf(b,c);for(;0<=c;c--)if(c in a&&a[c]===b)return c;return-1};_.ob=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e="string"===typeof a?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)};
_.pb=Array.prototype.filter?function(a,b){return Array.prototype.filter.call(a,b,void 0)}:function(a,b){for(var c=a.length,d=[],e=0,f="string"===typeof a?a.split(""):a,g=0;g<c;g++)if(g in f){var k=f[g];b.call(void 0,k,g,a)&&(d[e++]=k)}return d};_.qb=Array.prototype.map?function(a,b){return Array.prototype.map.call(a,b,void 0)}:function(a,b){for(var c=a.length,d=Array(c),e="string"===typeof a?a.split(""):a,f=0;f<c;f++)f in e&&(d[f]=b.call(void 0,e[f],f,a));return d};
_.rb=Array.prototype.some?function(a,b,c){return Array.prototype.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e="string"===typeof a?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return!0;return!1};_.sb=Array.prototype.every?function(a,b,c){return Array.prototype.every.call(a,b,c)}:function(a,b,c){for(var d=a.length,e="string"===typeof a?a.split(""):a,f=0;f<d;f++)if(f in e&&!b.call(c,e[f],f,a))return!1;return!0};
var vb;_.tb=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};
_.wb=function(a,b){var c=0;a=(0,_.tb)(String(a)).split(".");b=(0,_.tb)(String(b)).split(".");for(var d=Math.max(a.length,b.length),e=0;0==c&&e<d;e++){var f=a[e]||"",g=b[e]||"";do{f=/(\d*)(\D*)(.*)/.exec(f)||["","","",""];g=/(\d*)(\D*)(.*)/.exec(g)||["","","",""];if(0==f[0].length&&0==g[0].length)break;c=vb(0==f[1].length?0:parseInt(f[1],10),0==g[1].length?0:parseInt(g[1],10))||vb(0==f[2].length,0==g[2].length)||vb(f[2],g[2]);f=f[3];g=g[3]}while(0==c)}return c};
vb=function(a,b){return a<b?-1:a>b?1:0};
a:{var yb=_.A.navigator;if(yb){var zb=yb.userAgent;if(zb){_.xb=zb;break a}}_.xb=""}_.Bb=function(a){return-1!=_.xb.indexOf(a)};
var Eb;_.Db=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};Eb="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");_.Fb=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Eb.length;f++)c=Eb[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};
_.Gb=function(){return _.Bb("Opera")};_.Hb=function(){return _.Bb("Trident")||_.Bb("MSIE")};_.Ib=function(){return _.Bb("Firefox")||_.Bb("FxiOS")};_.Jb=function(){return(_.Bb("Chrome")||_.Bb("CriOS"))&&!_.Bb("Edge")};
_.Kb=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}};
var Lb;_.Mb=function(){if(void 0===Lb){var a=null,b=_.A.trustedTypes;if(b&&b.createPolicy)try{a=b.createPolicy("goog#html",{createHTML:mb,createScript:mb,createScriptURL:mb})}catch(c){_.A.console&&_.A.console.error(c.message)}Lb=a}return Lb};
var Ob,Nb;_.Pb=function(a,b){this.EN=a===Nb&&b||"";this.gR=Ob};_.Pb.prototype.Ph=!0;_.Pb.prototype.xd=_.ja(4);_.Qb=function(a){return a instanceof _.Pb&&a.constructor===_.Pb&&a.gR===Ob?a.EN:"type_error:Const"};_.Rb=function(a){return new _.Pb(Nb,a)};Ob={};Nb={};
_.Ub=function(a,b){this.OL=b===_.Sb?a:""};_.Ub.prototype.Ph=!0;_.Ub.prototype.xd=_.ja(3);_.Ub.prototype.zB=!0;_.Ub.prototype.Hh=_.ja(6);_.Sb={};_.Wb=new _.Ub("about:invalid#zClosurez",_.Sb);
_.Yb=function(a,b){this.NL=b===_.Xb?a:""};_.Yb.prototype.Ph=!0;_.Yb.prototype.xd=_.ja(2);_.Xb={};_.Zb=new _.Yb("",_.Xb);
_.$b={};_.ac=function(a,b){this.ML=b===_.$b?a:"";this.Ph=!0};_.cc=function(a){a=_.Qb(a);return 0===a.length?bc:new _.ac(a,_.$b)};_.ac.prototype.xd=_.ja(1);var bc=new _.ac("",_.$b);
var dc;_.ec=function(a,b,c){this.LL=c===dc?a:"";this.GS=b};_.ec.prototype.zB=!0;_.ec.prototype.Hh=_.ja(5);_.ec.prototype.Ph=!0;_.ec.prototype.xd=_.ja(0);_.fc=function(a){if(a instanceof _.ec&&a.constructor===_.ec)return a.LL;_.eb(a);return"type_error:SafeHtml"};dc={};_.gc=function(a,b){var c=_.Mb();a=c?c.createHTML(a):a;return new _.ec(a,b,dc)};_.hc=new _.ec(_.A.trustedTypes&&_.A.trustedTypes.emptyHTML||"",0,dc);_.ic=_.gc("<br>",0);
_.jc=_.Kb(function(){var a=document.createElement("div"),b=document.createElement("div");b.appendChild(document.createElement("div"));a.appendChild(b);b=a.firstChild.firstChild;a.innerHTML=_.fc(_.hc);return!b.parentElement});
_.kc=String.prototype.repeat?function(a,b){return a.repeat(b)}:function(a,b){return Array(b+1).join(a)};_.lc=2147483648*Math.random()|0;
_.mc=function(){return _.Bb("iPhone")&&!_.Bb("iPod")&&!_.Bb("iPad")};_.nc=function(){return _.mc()||_.Bb("iPad")||_.Bb("iPod")};
var oc=function(a){oc[" "](a);return a};oc[" "]=_.cb;_.pc=function(a,b){try{return oc(a[b]),!0}catch(c){}return!1};_.qc=function(a,b,c){return Object.prototype.hasOwnProperty.call(a,b)?a[b]:a[b]=c(b)};
var Gc,Jc,Oc,Sc;_.rc=_.Gb();_.sc=_.Hb();_.tc=_.Bb("Edge");_.uc=_.tc||_.sc;_.vc=_.Bb("Gecko")&&!(-1!=_.xb.toLowerCase().indexOf("webkit")&&!_.Bb("Edge"))&&!(_.Bb("Trident")||_.Bb("MSIE"))&&!_.Bb("Edge");_.wc=-1!=_.xb.toLowerCase().indexOf("webkit")&&!_.Bb("Edge");_.xc=_.wc&&_.Bb("Mobile");_.yc=_.Bb("Macintosh");_.zc=_.Bb("Windows");_.Ac=_.Bb("Linux")||_.Bb("CrOS");_.Bc=_.Bb("Android");_.Cc=_.mc();_.Dc=_.Bb("iPad");_.Ec=_.Bb("iPod");_.Fc=_.nc();
Gc=function(){var a=_.A.document;return a?a.documentMode:void 0};a:{var Kc="",Lc=function(){var a=_.xb;if(_.vc)return/rv:([^\);]+)(\)|;)/.exec(a);if(_.tc)return/Edge\/([\d\.]+)/.exec(a);if(_.sc)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(_.wc)return/WebKit\/(\S+)/.exec(a);if(_.rc)return/(?:Version)[ \/]?(\S+)/.exec(a)}();Lc&&(Kc=Lc?Lc[1]:"");if(_.sc){var Mc=Gc();if(null!=Mc&&Mc>parseFloat(Kc)){Jc=String(Mc);break a}}Jc=Kc}_.Nc=Jc;Oc={};
_.Pc=function(a){return _.qc(Oc,a,function(){return 0<=_.wb(_.Nc,a)})};_.Rc=function(a){return Number(_.Qc)>=a};if(_.A.document&&_.sc){var Tc=Gc();Sc=Tc?Tc:parseInt(_.Nc,10)||void 0}else Sc=void 0;_.Qc=Sc;

/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var Yc,Zc,$c,bd,dd,fd,gd,hd,id,jd,kd,ld,nd,ud,vd,wd,xd,Fd,Gd;_.Uc=function(a,b){return _.ea[a]=b};_.Vc=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,_.Vc);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};_.Wc=function(a){return Array.prototype.concat.apply([],arguments)};_.Xc=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};_.Ub.prototype.Hh=_.Uc(6,function(){return 1});_.ec.prototype.Hh=_.Uc(5,function(){return this.GS});
_.Pb.prototype.xd=_.Uc(4,function(){return this.EN});_.Ub.prototype.xd=_.Uc(3,function(){return this.OL.toString()});_.Yb.prototype.xd=_.Uc(2,function(){return this.NL});_.ac.prototype.xd=_.Uc(1,function(){return this.ML});_.ec.prototype.xd=_.Uc(0,function(){return this.LL.toString()});Yc=null;Zc=/^[\w+/_-]+[=]{0,2}$/;$c=function(a){return(a=a.querySelector&&a.querySelector("script[nonce]"))&&(a=a.nonce||a.getAttribute("nonce"))&&Zc.test(a)?a:""};
_.ad=function(a){if(a&&a!=_.A)return $c(a.document);null===Yc&&(Yc=$c(_.A.document));return Yc};bd=0;_.cd=function(a){return Object.prototype.hasOwnProperty.call(a,_.Ya)&&a[_.Ya]||(a[_.Ya]=++bd)};_.K(_.Vc,Error);_.Vc.prototype.name="CustomError";_.ed=function(a,b){return 0==a.lastIndexOf(b,0)};fd=/&/g;gd=/</g;hd=/>/g;id=/"/g;jd=/'/g;kd=/\x00/g;ld=/[\x00&<>"']/;
_.md=function(a,b){if(b)a=a.replace(fd,"&amp;").replace(gd,"&lt;").replace(hd,"&gt;").replace(id,"&quot;").replace(jd,"&#39;").replace(kd,"&#0;");else{if(!ld.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(fd,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(gd,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(hd,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(id,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(jd,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(kd,"&#0;"))}return a};nd={};
_.od=function(a,b){this.PL=b===nd?a:""};_.od.prototype.Ph=!0;_.od.prototype.xd=function(){return this.PL.toString()};_.od.prototype.zB=!0;_.od.prototype.Hh=function(){return 1};_.pd=function(a){if(a instanceof _.od&&a.constructor===_.od)return a.PL;_.eb(a);return"type_error:TrustedResourceUrl"};_.qd=function(a){return _.pd(a).toString()};_.rd=function(a){var b=_.Mb();a=b?b.createScriptURL(a):a;return new _.od(a,nd)};_.sd=function(a){return _.rd(_.Qb(a))};
_.td=function(a){if(a instanceof _.Ub&&a.constructor===_.Ub)return a.OL;_.eb(a);return"type_error:SafeUrl"};ud=/^(?:audio\/(?:3gpp2|3gpp|aac|L16|midi|mp3|mp4|mpeg|oga|ogg|opus|x-m4a|x-matroska|x-wav|wav|webm)|font\/\w+|image\/(?:bmp|gif|jpeg|jpg|png|tiff|webp|x-icon)|video\/(?:mpeg|mp4|ogg|webm|quicktime|x-matroska))(?:;\w+=(?:\w+|"[\w;,= ]+"))*$/i;vd=/^data:(.*);base64,[a-z0-9+\/]+=*$/i;
wd=function(a){a=String(a);a=a.replace(/(%0A|%0D)/g,"");var b=a.match(vd);return b&&ud.test(b[1])?new _.Ub(a,_.Sb):null};xd=/^(?:(?:https?|mailto|ftp):|[^:/?#]*(?:[/?#]|$))/i;_.yd=function(a){if(a instanceof _.Ub)return a;a="object"==typeof a&&a.Ph?a.xd():String(a);return xd.test(a)?new _.Ub(a,_.Sb):wd(a)};
_.zd=function(a,b){if(a instanceof _.Ub)return a;a="object"==typeof a&&a.Ph?a.xd():String(a);if(b&&/^data:/i.test(a)&&(b=wd(a)||_.Wb,b.xd()==a))return b;xd.test(a)||(a="about:invalid#zClosurez");return new _.Ub(a,_.Sb)};_.Ad=function(a){if(a instanceof _.ec)return a;var b="object"==typeof a,c=null;b&&a.zB&&(c=a.Hh());return _.gc(_.md(b&&a.Ph?a.xd():String(a)),c)};_.Bd=function(a,b){if((0,_.jc)())for(;a.lastChild;)a.removeChild(a.lastChild);a.innerHTML=_.fc(b)};
_.Cd=function(a,b){b=b instanceof _.Ub?b:_.zd(b);a.href=_.td(b)};_.Dd=function(a,b,c,d){a=a instanceof _.Ub?a:_.zd(a);c=c instanceof _.Pb?_.Qb(c):c||"";return(b||_.A).open(_.td(a),c,d,void 0)};_.Ed=function(a){return a=_.md(a,void 0)};Fd=!_.sc||_.Rc(9);Gd=!_.vc&&!_.sc||_.sc&&_.Rc(9)||_.vc&&_.Pc("1.9.1");_.Hd=_.sc&&!_.Pc("9");_.Id=_.sc||_.rc||_.wc;_.Md=_.sc&&!_.Rc(9);
var Sd,Wd;_.Pd=function(a){return a?new _.Nd(_.Od(a)):dd||(dd=new _.Nd)};_.Qd=function(a,b){return"string"===typeof b?a.getElementById(b):b};
_.Rd=function(a,b,c,d){a=d||a;b=b&&"*"!=b?String(b).toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(b||c))return a.querySelectorAll(b+(c?"."+c:""));if(c&&a.getElementsByClassName){a=a.getElementsByClassName(c);if(b){d={};for(var e=0,f=0,g;g=a[f];f++)b==g.nodeName&&(d[e++]=g);d.length=e;return d}return a}a=a.getElementsByTagName(b||"*");if(c){d={};for(f=e=0;g=a[f];f++)b=g.className,"function"==typeof b.split&&_.$a(b.split(/\s+/),c)&&(d[e++]=g);d.length=e;return d}return a};
_.Td=function(a,b){_.Db(b,function(c,d){c&&"object"==typeof c&&c.Ph&&(c=c.xd());"style"==d?a.style.cssText=c:"class"==d?a.className=c:"for"==d?a.htmlFor=c:Sd.hasOwnProperty(d)?a.setAttribute(Sd[d],c):_.ed(d,"aria-")||_.ed(d,"data-")?a.setAttribute(d,c):a[d]=c})};Sd={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};
_.Ud=function(a){return a?a.parentWindow||a.defaultView:window};_.Xd=function(a,b){var c=String(b[0]),d=b[1];if(!Fd&&d&&(d.name||d.type)){c=["<",c];d.name&&c.push(' name="',_.Ed(d.name),'"');if(d.type){c.push(' type="',_.Ed(d.type),'"');var e={};_.Fb(e,d);delete e.type;d=e}c.push(">");c=c.join("")}c=_.Vd(a,c);d&&("string"===typeof d?c.className=d:Array.isArray(d)?c.className=d.join(" "):_.Td(c,d));2<b.length&&Wd(a,c,b,2);return c};
Wd=function(a,b,c,d){function e(k){k&&b.appendChild("string"===typeof k?a.createTextNode(k):k)}for(;d<c.length;d++){var f=c[d];if(!_.hb(f)||_.bb(f)&&0<f.nodeType)e(f);else{a:{if(f&&"number"==typeof f.length){if(_.bb(f)){var g="function"==typeof f.item||"string"==typeof f.item;break a}if("function"===typeof f){g="function"==typeof f.item;break a}}g=!1}_.ob(g?_.Xc(f):f,e)}}};_.Zd=function(a){return _.Vd(document,a)};
_.Vd=function(a,b){b=String(b);"application/xhtml+xml"===a.contentType&&(b=b.toLowerCase());return a.createElement(b)};_.$d=function(a){if(1!=a.nodeType)return!1;switch(a.tagName){case "APPLET":case "AREA":case "BASE":case "BR":case "COL":case "COMMAND":case "EMBED":case "FRAME":case "HR":case "IMG":case "INPUT":case "IFRAME":case "ISINDEX":case "KEYGEN":case "LINK":case "NOFRAMES":case "NOSCRIPT":case "META":case "OBJECT":case "PARAM":case "SCRIPT":case "SOURCE":case "STYLE":case "TRACK":case "WBR":return!1}return!0};
_.ae=function(a,b){Wd(_.Od(a),a,arguments,1)};_.be=function(a){for(var b;b=a.firstChild;)a.removeChild(b)};_.ce=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b)};_.de=function(a){return a&&a.parentNode?a.parentNode.removeChild(a):null};_.ee=function(a){var b,c=a.parentNode;if(c&&11!=c.nodeType){if(a.removeNode)return a.removeNode(!1);for(;b=a.firstChild;)c.insertBefore(b,a);return _.de(a)}};
_.fe=function(a){return Gd&&void 0!=a.children?a.children:_.pb(a.childNodes,function(b){return 1==b.nodeType})};_.ge=function(a){return _.bb(a)&&1==a.nodeType};_.he=function(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};_.Od=function(a){return 9==a.nodeType?a:a.ownerDocument||a.document};
_.ie=function(a,b){if("textContent"in a)a.textContent=b;else if(3==a.nodeType)a.data=String(b);else if(a.firstChild&&3==a.firstChild.nodeType){for(;a.lastChild!=a.firstChild;)a.removeChild(a.lastChild);a.firstChild.data=String(b)}else _.be(a),a.appendChild(_.Od(a).createTextNode(String(b)))};_.Nd=function(a){this.rb=a||_.A.document||document};_.h=_.Nd.prototype;_.h.Fa=_.Pd;_.h.ND=_.ja(7);_.h.ub=function(){return this.rb};_.h.H=function(a){return _.Qd(this.rb,a)};
_.h.getElementsByTagName=function(a,b){return(b||this.rb).getElementsByTagName(String(a))};_.h.ta=function(a,b,c){return _.Xd(this.rb,arguments)};_.h.createElement=function(a){return _.Vd(this.rb,a)};_.h.createTextNode=function(a){return this.rb.createTextNode(String(a))};_.h.Ab=function(){var a=this.rb;return a.parentWindow||a.defaultView};_.h.appendChild=function(a,b){a.appendChild(b)};_.h.append=_.ae;_.h.canHaveChildren=_.$d;_.h.Nd=_.be;_.h.ZJ=_.ce;_.h.removeNode=_.de;_.h.qT=_.ee;_.h.lA=_.fe;
_.h.isElement=_.ge;_.h.contains=_.he;_.h.Sh=_.ja(8);
/*
 gapi.loader.OBJECT_CREATE_TEST_OVERRIDE &&*/
_.je=window;_.ke=document;_.le=_.je.location;_.me=/\[native code\]/;_.ne=function(a,b,c){return a[b]=a[b]||c};_.oe=function(){var a;if((a=Object.create)&&_.me.test(a))a=a(null);else{a={};for(var b in a)a[b]=void 0}return a};_.pe=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};_.qe=function(a,b){a=a||{};for(var c in a)_.pe(a,c)&&(b[c]=a[c])};_.re=_.ne(_.je,"gapi",{});
_.te=function(a,b,c){var d=new RegExp("([#].*&|[#])"+b+"=([^&#]*)","g");b=new RegExp("([?#].*&|[?#])"+b+"=([^&#]*)","g");if(a=a&&(d.exec(a)||b.exec(a)))try{c=decodeURIComponent(a[2])}catch(e){}return c};_.ue=new RegExp(/^/.source+/([a-zA-Z][-+.a-zA-Z0-9]*:)?/.source+/(\/\/[^\/?#]*)?/.source+/([^?#]*)?/.source+/(\?([^#]*))?/.source+/(#((#|[^#])*))?/.source+/$/.source);_.ve=new RegExp(/(%([^0-9a-fA-F%]|[0-9a-fA-F]([^0-9a-fA-F%])?)?)*/.source+/%($|[^0-9a-fA-F]|[0-9a-fA-F]($|[^0-9a-fA-F]))/.source,"g");
_.we=new RegExp(/\/?\??#?/.source+"("+/[\/?#]/i.source+"|"+/[\uD800-\uDBFF]/i.source+"|"+/%[c-f][0-9a-f](%[89ab][0-9a-f]){0,2}(%[89ab]?)?/i.source+"|"+/%[0-9a-f]?/i.source+")$","i");
_.ye=function(a,b,c){_.xe(a,b,c,"add","at")};_.xe=function(a,b,c,d,e){if(a[d+"EventListener"])a[d+"EventListener"](b,c,!1);else if(a[e+"tachEvent"])a[e+"tachEvent"]("on"+b,c)};
_.ze=_.ne(_.je,"___jsl",_.oe());_.ne(_.ze,"I",0);_.ne(_.ze,"hel",10);
var Ae,Be,Ce,De,Ee,Fe,Ge;Ae=function(a){var b=window.___jsl=window.___jsl||{};b[a]=b[a]||[];return b[a]};Be=function(a){var b=window.___jsl=window.___jsl||{};b.cfg=!a&&b.cfg||{};return b.cfg};Ce=function(a){return"object"===typeof a&&/\[native code\]/.test(a.push)};
De=function(a,b,c){if(b&&"object"===typeof b)for(var d in b)!Object.prototype.hasOwnProperty.call(b,d)||c&&"___goc"===d&&"undefined"===typeof b[d]||(a[d]&&b[d]&&"object"===typeof a[d]&&"object"===typeof b[d]&&!Ce(a[d])&&!Ce(b[d])?De(a[d],b[d]):b[d]&&"object"===typeof b[d]?(a[d]=Ce(b[d])?[]:{},De(a[d],b[d])):a[d]=b[d])};
Ee=function(a){if(a&&!/^\s+$/.test(a)){for(;0==a.charCodeAt(a.length-1);)a=a.substring(0,a.length-1);try{var b=window.JSON.parse(a)}catch(c){}if("object"===typeof b)return b;try{b=(new Function("return ("+a+"\n)"))()}catch(c){}if("object"===typeof b)return b;try{b=(new Function("return ({"+a+"\n})"))()}catch(c){}return"object"===typeof b?b:{}}};
Fe=function(a,b){var c={___goc:void 0};a.length&&a[a.length-1]&&Object.hasOwnProperty.call(a[a.length-1],"___goc")&&"undefined"===typeof a[a.length-1].___goc&&(c=a.pop());De(c,b);a.push(c)};
Ge=function(a){Be(!0);var b=window.___gcfg,c=Ae("cu"),d=window.___gu;b&&b!==d&&(Fe(c,b),window.___gu=b);b=Ae("cu");var e=document.scripts||document.getElementsByTagName("script")||[];d=[];var f=[];f.push.apply(f,Ae("us"));for(var g=0;g<e.length;++g)for(var k=e[g],l=0;l<f.length;++l)k.src&&0==k.src.indexOf(f[l])&&d.push(k);0==d.length&&0<e.length&&e[e.length-1].src&&d.push(e[e.length-1]);for(e=0;e<d.length;++e)d[e].getAttribute("gapi_processed")||(d[e].setAttribute("gapi_processed",!0),(f=d[e])?(g=
f.nodeType,f=3==g||4==g?f.nodeValue:f.textContent||f.innerText||f.innerHTML||""):f=void 0,(f=Ee(f))&&b.push(f));a&&Fe(c,a);d=Ae("cd");a=0;for(b=d.length;a<b;++a)De(Be(),d[a],!0);d=Ae("ci");a=0;for(b=d.length;a<b;++a)De(Be(),d[a],!0);a=0;for(b=c.length;a<b;++a)De(Be(),c[a],!0)};_.S=function(a,b){var c=Be();if(!a)return c;a=a.split("/");for(var d=0,e=a.length;c&&"object"===typeof c&&d<e;++d)c=c[a[d]];return d===a.length&&void 0!==c?c:b};
_.He=function(a,b){var c;if("string"===typeof a){var d=c={};a=a.split("/");for(var e=0,f=a.length;e<f-1;++e){var g={};d=d[a[e]]=g}d[a[e]]=b}else c=a;Ge(c)};
var Ie=function(){var a=window.__GOOGLEAPIS;a&&(a.googleapis&&!a["googleapis.config"]&&(a["googleapis.config"]=a.googleapis),_.ne(_.ze,"ci",[]).push(a),window.__GOOGLEAPIS=void 0)};
Ie&&Ie();Ge();
_.C("gapi.config.get",_.S);_.C("gapi.config.update",_.He);

_.Je=function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(_.hb(d)){var e=a.length||0,f=d.length||0;a.length=e+f;for(var g=0;g<f;g++)a[e+g]=d[g]}else a.push(d)}};_.Ke=function(a){for(var b={},c=0,d=0;d<a.length;){var e=a[d++];var f=e;f=_.bb(f)?"o"+_.cd(f):(typeof f).charAt(0)+f;Object.prototype.hasOwnProperty.call(b,f)||(b[f]=!0,a[c++]=e)}a.length=c};_.Le=function(a,b){for(var c in a)if(a[c]==b)return!0;return!1};_.Me=function(a){return/^[\s\xa0]*$/.test(a)};
_.Ne=function(a,b){var c=b||document;if(c.getElementsByClassName)a=c.getElementsByClassName(a)[0];else{c=document;var d=b||c;a=d.querySelectorAll&&d.querySelector&&a?d.querySelector(a?"."+a:""):_.Rd(c,"*",a,b)[0]||null}return a||null};

/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
_.lh=function(a){return encodeURIComponent(String(a))};_.mh=function(a){return null==a?"":String(a)};_.nh=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^\\/?#]*)@)?([^\\/?#]*?)(?::([0-9]+))?(?=[\\/?#]|$))?([^?#]+)?(?:\?([^#]*))?(?:#([\s\S]*))?$/;_.oh=function(a,b){if(!b)return a;var c=a.indexOf("#");0>c&&(c=a.length);var d=a.indexOf("?");if(0>d||d>c){d=c;var e=""}else e=a.substring(d+1,c);a=[a.substr(0,d),e,a.substr(c)];c=a[1];a[1]=b?c?c+"&"+b:b:c;return a[0]+(a[1]?"?"+a[1]:"")+a[2]};
_.ph=function(a,b,c){if(Array.isArray(b))for(var d=0;d<b.length;d++)_.ph(a,String(b[d]),c);else null!=b&&c.push(a+(""===b?"":"="+_.lh(b)))};_.qh=function(a){var b=[],c;for(c in a)_.ph(c,a[c],b);return b.join("&")};_.rh=function(a,b){b=_.qh(b);return _.oh(a,b)};

/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/

/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
_.hi=function(a,b){a:{for(var c=a.length,d="string"===typeof a?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a)){b=e;break a}b=-1}return 0>b?null:"string"===typeof a?a.charAt(b):a[b]};_.ii=function(a,b){a.prototype=(0,_.Ja)(b.prototype);a.prototype.constructor=a;if(_.Ra)(0,_.Ra)(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.T=b.prototype};
_.ji=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var d=c.slice();d.push.apply(d,arguments);return a.apply(this,d)}};_.ki=[];_.li=[];_.mi=!1;_.ni=function(a){_.ki[_.ki.length]=a;if(_.mi)for(var b=0;b<_.li.length;b++)a((0,_.R)(_.li[b].wrap,_.li[b]))};

/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var qi;_.oi=function(a,b){b=(0,_.Za)(a,b);var c;(c=0<=b)&&Array.prototype.splice.call(a,b,1);return c};_.pi=function(a,b){a=a.split(".");b=b||_.A;for(var c=0;c<a.length;c++)if(b=b[a[c]],null==b)return null;return b};qi=function(a,b){for(var c in a)if(b.call(void 0,a[c],c,a))return!0;return!1};
_.ri=function(){this.Ob=this.Ob;this.km=this.km};_.ri.prototype.Ob=!1;_.ri.prototype.Vn=function(){return this.Ob};_.ri.prototype.Da=function(){this.Ob||(this.Ob=!0,this.va())};_.ui=function(a,b){_.si(a,_.ji(_.ti,b))};_.si=function(a,b){a.Ob?b():(a.km||(a.km=[]),a.km.push(b))};_.ri.prototype.va=function(){if(this.km)for(;this.km.length;)this.km.shift()()};_.ti=function(a){a&&"function"==typeof a.Da&&a.Da()};
_.vi=function(a,b){this.type=a;this.currentTarget=this.target=b;this.defaultPrevented=this.wm=!1};_.vi.prototype.stopPropagation=function(){this.wm=!0};_.vi.prototype.preventDefault=function(){this.defaultPrevented=!0};
var xi,yi;_.wi=!_.sc||_.Rc(9);xi=!_.sc||_.Rc(9);yi=_.sc&&!_.Pc("9");!_.wc||_.Pc("528");_.vc&&_.Pc("1.9b")||_.sc&&_.Pc("8")||_.rc&&_.Pc("9.5")||_.wc&&_.Pc("528");_.vc&&!_.Pc("8")||_.sc&&_.Pc("9");var zi=function(){if(!_.A.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{_.A.addEventListener("test",_.cb,b),_.A.removeEventListener("test",_.cb,b)}catch(c){}return a}();
_.Ai=function(a,b){_.vi.call(this,a?a.type:"");this.relatedTarget=this.currentTarget=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=this.offsetY=this.offsetX=0;this.key="";this.charCode=this.keyCode=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.state=null;this.TC=!1;this.pointerId=0;this.pointerType="";this.xe=null;a&&this.init(a,b)};_.K(_.Ai,_.vi);var Bi={2:"touch",3:"pen",4:"mouse"};
_.Ai.prototype.init=function(a,b){var c=this.type=a.type,d=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.currentTarget=b;(b=a.relatedTarget)?_.vc&&(_.pc(b,"nodeName")||(b=null)):"mouseover"==c?b=a.fromElement:"mouseout"==c&&(b=a.toElement);this.relatedTarget=b;d?(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0):(this.offsetX=_.wc||void 0!==
a.offsetX?a.offsetX:a.layerX,this.offsetY=_.wc||void 0!==a.offsetY?a.offsetY:a.layerY,this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||0,this.screenY=a.screenY||0);this.button=a.button;this.keyCode=a.keyCode||0;this.key=a.key||"";this.charCode=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.TC=_.yc?a.metaKey:a.ctrlKey;this.pointerId=a.pointerId||
0;this.pointerType="string"===typeof a.pointerType?a.pointerType:Bi[a.pointerType]||"";this.state=a.state;this.xe=a;a.defaultPrevented&&this.preventDefault()};_.Ai.prototype.stopPropagation=function(){_.Ai.T.stopPropagation.call(this);this.xe.stopPropagation?this.xe.stopPropagation():this.xe.cancelBubble=!0};
_.Ai.prototype.preventDefault=function(){_.Ai.T.preventDefault.call(this);var a=this.xe;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,yi)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};
var Ei;_.Ci="closure_listenable_"+(1E6*Math.random()|0);_.Di=function(a){return!(!a||!a[_.Ci])};Ei=0;
var Fi=function(a,b,c,d,e){this.listener=a;this.tw=null;this.src=b;this.type=c;this.capture=!!d;this.Ye=e;this.key=++Ei;this.ro=this.Bt=!1},Gi=function(a){a.ro=!0;a.listener=null;a.tw=null;a.src=null;a.Ye=null};
_.Hi=function(a){this.src=a;this.yd={};this.Es=0};_.Hi.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.yd[f];a||(a=this.yd[f]=[],this.Es++);var g=Ii(a,b,d,e);-1<g?(b=a[g],c||(b.Bt=!1)):(b=new Fi(b,this.src,f,!!d,e),b.Bt=c,a.push(b));return b};_.Hi.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.yd))return!1;var e=this.yd[a];b=Ii(e,b,c,d);return-1<b?(Gi(e[b]),Array.prototype.splice.call(e,b,1),0==e.length&&(delete this.yd[a],this.Es--),!0):!1};
_.Ji=function(a,b){var c=b.type;if(!(c in a.yd))return!1;var d=_.oi(a.yd[c],b);d&&(Gi(b),0==a.yd[c].length&&(delete a.yd[c],a.Es--));return d};_.Hi.prototype.removeAll=function(a){a=a&&a.toString();var b=0,c;for(c in this.yd)if(!a||c==a){for(var d=this.yd[c],e=0;e<d.length;e++)++b,Gi(d[e]);delete this.yd[c];this.Es--}return b};_.Hi.prototype.Bn=function(a,b,c,d){a=this.yd[a.toString()];var e=-1;a&&(e=Ii(a,b,c,d));return-1<e?a[e]:null};
_.Hi.prototype.hasListener=function(a,b){var c=void 0!==a,d=c?a.toString():"",e=void 0!==b;return qi(this.yd,function(f){for(var g=0;g<f.length;++g)if(!(c&&f[g].type!=d||e&&f[g].capture!=b))return!0;return!1})};var Ii=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.ro&&f.listener==b&&f.capture==!!c&&f.Ye==d)return e}return-1};
var Ki,Li,Mi,Qi,Si,Ti,Xi,Wi,Ui,Yi;Ki="closure_lm_"+(1E6*Math.random()|0);Li={};Mi=0;_.Oi=function(a,b,c,d,e){if(d&&d.once)return _.Ni(a,b,c,d,e);if(Array.isArray(b)){for(var f=0;f<b.length;f++)_.Oi(a,b[f],c,d,e);return null}c=_.Pi(c);return _.Di(a)?a.V(b,c,_.bb(d)?!!d.capture:!!d,e):Qi(a,b,c,!1,d,e)};
Qi=function(a,b,c,d,e,f){if(!b)throw Error("z");var g=_.bb(e)?!!e.capture:!!e,k=_.Ri(a);k||(a[Ki]=k=new _.Hi(a));c=k.add(b,c,d,g,f);if(c.tw)return c;d=Si();c.tw=d;d.src=a;d.listener=c;if(a.addEventListener)zi||(e=g),void 0===e&&(e=!1),a.addEventListener(b.toString(),d,e);else if(a.attachEvent)a.attachEvent(Ti(b.toString()),d);else if(a.addListener&&a.removeListener)a.addListener(d);else throw Error("A");Mi++;return c};
Si=function(){var a=Ui,b=xi?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b};_.Ni=function(a,b,c,d,e){if(Array.isArray(b)){for(var f=0;f<b.length;f++)_.Ni(a,b[f],c,d,e);return null}c=_.Pi(c);return _.Di(a)?a.eo(b,c,_.bb(d)?!!d.capture:!!d,e):Qi(a,b,c,!0,d,e)};
_.Vi=function(a){if("number"===typeof a||!a||a.ro)return!1;var b=a.src;if(_.Di(b))return b.CE(a);var c=a.type,d=a.tw;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent(Ti(c),d):b.addListener&&b.removeListener&&b.removeListener(d);Mi--;(c=_.Ri(b))?(_.Ji(c,a),0==c.Es&&(c.src=null,b[Ki]=null)):Gi(a);return!0};Ti=function(a){return a in Li?Li[a]:Li[a]="on"+a};
Xi=function(a,b,c,d){var e=!0;if(a=_.Ri(a))if(b=a.yd[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.capture==c&&!f.ro&&(f=Wi(f,d),e=e&&!1!==f)}return e};Wi=function(a,b){var c=a.listener,d=a.Ye||a.src;a.Bt&&_.Vi(a);return c.call(d,b)};
Ui=function(a,b){if(a.ro)return!0;if(!xi){var c=b||_.pi("window.event");b=new _.Ai(c,this);var d=!0;if(!(0>c.keyCode||void 0!=c.returnValue)){a:{var e=!1;if(0==c.keyCode)try{c.keyCode=-1;break a}catch(g){e=!0}if(e||void 0==c.returnValue)c.returnValue=!0}c=[];for(e=b.currentTarget;e;e=e.parentNode)c.push(e);a=a.type;for(e=c.length-1;!b.wm&&0<=e;e--){b.currentTarget=c[e];var f=Xi(c[e],a,!0,b);d=d&&f}for(e=0;!b.wm&&e<c.length;e++)b.currentTarget=c[e],f=Xi(c[e],a,!1,b),d=d&&f}return d}return Wi(a,new _.Ai(b,
this))};_.Ri=function(a){a=a[Ki];return a instanceof _.Hi?a:null};Yi="__closure_events_fn_"+(1E9*Math.random()>>>0);_.Pi=function(a){if("function"===typeof a)return a;a[Yi]||(a[Yi]=function(b){return a.handleEvent(b)});return a[Yi]};_.ni(function(a){Ui=a(Ui)});

/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
_.Zi=function(a,b){var c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c};_.$i=function(a){for(var b in a)return!1;return!0};_.cj=function(a,b,c,d,e){if(Array.isArray(b))for(var f=0;f<b.length;f++)_.cj(a,b[f],c,d,e);else d=_.bb(d)?!!d.capture:!!d,c=_.Pi(c),_.Di(a)?a.$b(b,c,d,e):a&&(a=_.Ri(a))&&(b=a.Bn(b,c,d,e))&&_.Vi(b)};_.dj=function(){_.ri.call(this);this.Pi=new _.Hi(this);this.CR=this;this.OC=null};_.K(_.dj,_.ri);_.dj.prototype[_.Ci]=!0;_.h=_.dj.prototype;_.h.Jl=function(){return this.OC};
_.h.Sw=_.ja(12);_.h.addEventListener=function(a,b,c,d){_.Oi(this,a,b,c,d)};_.h.removeEventListener=function(a,b,c,d){_.cj(this,a,b,c,d)};
_.h.dispatchEvent=function(a){var b,c=this.Jl();if(c)for(b=[];c;c=c.Jl())b.push(c);c=this.CR;var d=a.type||a;if("string"===typeof a)a=new _.vi(a,c);else if(a instanceof _.vi)a.target=a.target||c;else{var e=a;a=new _.vi(d,c);_.Fb(a,e)}e=!0;if(b)for(var f=b.length-1;!a.wm&&0<=f;f--){var g=a.currentTarget=b[f];e=g.gq(d,!0,a)&&e}a.wm||(g=a.currentTarget=c,e=g.gq(d,!0,a)&&e,a.wm||(e=g.gq(d,!1,a)&&e));if(b)for(f=0;!a.wm&&f<b.length;f++)g=a.currentTarget=b[f],e=g.gq(d,!1,a)&&e;return e};
_.h.va=function(){_.dj.T.va.call(this);this.cD();this.OC=null};_.h.V=function(a,b,c,d){return this.Pi.add(String(a),b,!1,c,d)};_.h.eo=function(a,b,c,d){return this.Pi.add(String(a),b,!0,c,d)};_.h.$b=function(a,b,c,d){return this.Pi.remove(String(a),b,c,d)};_.h.CE=function(a){return _.Ji(this.Pi,a)};_.h.cD=function(a){this.Pi&&this.Pi.removeAll(a)};
_.h.gq=function(a,b,c){a=this.Pi.yd[String(a)];if(!a)return!0;a=a.concat();for(var d=!0,e=0;e<a.length;++e){var f=a[e];if(f&&!f.ro&&f.capture==b){var g=f.listener,k=f.Ye||f.src;f.Bt&&this.CE(f);d=!1!==g.call(k,c)&&d}}return d&&!c.defaultPrevented};_.h.Bn=function(a,b,c,d){return this.Pi.Bn(String(a),b,c,d)};_.h.hasListener=function(a,b){return this.Pi.hasListener(void 0!==a?String(a):void 0,b)};

/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/

/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var rk;_.kk=function(a,b){for(var c in a)if(!(c in b)||a[c]!==b[c])return!1;for(var d in b)if(!(d in a))return!1;return!0};_.lk=function(a){var b={},c;for(c in a)b[c]=a[c];return b};_.mk=function(a){return a};_.nk=function(a,b){a.src=_.pd(b);(b=_.ad(a.ownerDocument&&a.ownerDocument.defaultView))&&a.setAttribute("nonce",b)};_.ok=function(a){var b=window.location;a=a instanceof _.Ub?a:_.zd(a);b.href=_.td(a)};_.pk=function(a){a.prototype.$goog_Thenable=!0};_.qk=function(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};
rk=function(a,b){this.DS=a;this.XZ=b;this.Yv=0;this.Ze=null};rk.prototype.get=function(){if(0<this.Yv){this.Yv--;var a=this.Ze;this.Ze=a.next;a.next=null}else a=this.DS();return a};rk.prototype.put=function(a){this.XZ(a);100>this.Yv&&(this.Yv++,a.next=this.Ze,this.Ze=a)};
var sk,uk,vk,tk;sk=function(a){_.A.setTimeout(function(){throw a;},0)};_.wk=function(a){a=tk(a);"function"!==typeof _.A.setImmediate||_.A.Window&&_.A.Window.prototype&&!_.Bb("Edge")&&_.A.Window.prototype.setImmediate==_.A.setImmediate?(uk||(uk=vk()),uk(a)):_.A.setImmediate(a)};
vk=function(){var a=_.A.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&!_.Bb("Presto")&&(a=function(){var e=_.Zd("IFRAME");e.style.display="none";document.documentElement.appendChild(e);var f=e.contentWindow;e=f.document;e.open();e.close();var g="callImmediate"+Math.random(),k="file:"==f.location.protocol?"*":f.location.protocol+"//"+f.location.host;e=(0,_.R)(function(l){if(("*"==k||l.origin==k)&&l.data==g)this.port1.onmessage()},this);
f.addEventListener("message",e,!1);this.port1={};this.port2={postMessage:function(){f.postMessage(g,k)}}});if("undefined"!==typeof a&&!_.Hb()){var b=new a,c={},d=c;b.port1.onmessage=function(){if(void 0!==c.next){c=c.next;var e=c.cb;c.cb=null;e()}};return function(e){d.next={cb:e};d=d.next;b.port2.postMessage(0)}}return function(e){_.A.setTimeout(e,0)}};tk=_.mk;_.ni(function(a){tk=a});
var xk=function(){this.yx=this.Uo=null},zk=new rk(function(){return new yk},function(a){a.reset()});xk.prototype.add=function(a,b){var c=zk.get();c.set(a,b);this.yx?this.yx.next=c:this.Uo=c;this.yx=c};xk.prototype.remove=function(){var a=null;this.Uo&&(a=this.Uo,this.Uo=this.Uo.next,this.Uo||(this.yx=null),a.next=null);return a};var yk=function(){this.next=this.scope=this.Wg=null};yk.prototype.set=function(a,b){this.Wg=a;this.scope=b;this.next=null};
yk.prototype.reset=function(){this.next=this.scope=this.Wg=null};
var Ak,Bk,Ck,Dk,Fk;_.Ek=function(a,b){Ak||Bk();Ck||(Ak(),Ck=!0);Dk.add(a,b)};Bk=function(){if(_.A.Promise&&_.A.Promise.resolve){var a=_.A.Promise.resolve(void 0);Ak=function(){a.then(Fk)}}else Ak=function(){_.wk(Fk)}};Ck=!1;Dk=new xk;Fk=function(){for(var a;a=Dk.remove();){try{a.Wg.call(a.scope)}catch(b){sk(b)}zk.put(a)}Ck=!1};
var Hk,Ik,Tk,Rk;_.Gk=function(a,b){this.Ea=0;this.ij=void 0;this.ln=this.Qj=this.$a=null;this.Pu=this.Qz=!1;if(a!=_.cb)try{var c=this;a.call(b,function(d){c.lh(2,d)},function(d){c.lh(3,d)})}catch(d){this.lh(3,d)}};Hk=function(){this.next=this.context=this.jo=this.xr=this.ol=null;this.rp=!1};Hk.prototype.reset=function(){this.context=this.jo=this.xr=this.ol=null;this.rp=!1};Ik=new rk(function(){return new Hk},function(a){a.reset()});_.Jk=function(a,b,c){var d=Ik.get();d.xr=a;d.jo=b;d.context=c;return d};
_.Kk=function(a){if(a instanceof _.Gk)return a;var b=new _.Gk(_.cb);b.lh(2,a);return b};_.Lk=function(a){return new _.Gk(function(b,c){c(a)})};_.Nk=function(a,b,c){Mk(a,b,c,null)||_.Ek(_.ji(b,a))};_.Ok=function(a){return new _.Gk(function(b,c){var d=a.length,e=[];if(d)for(var f=function(m,n){d--;e[m]=n;0==d&&b(e)},g=function(m){c(m)},k=0,l;k<a.length;k++)l=a[k],_.Nk(l,_.ji(f,k),g);else b(e)})};_.Qk=function(){var a,b,c=new _.Gk(function(d,e){a=d;b=e});return new Pk(c,a,b)};
_.Gk.prototype.then=function(a,b,c){return Rk(this,"function"===typeof a?a:null,"function"===typeof b?b:null,c)};_.pk(_.Gk);_.Gk.prototype.ys=function(a,b){return Rk(this,null,a,b)};_.Gk.prototype.cancel=function(a){if(0==this.Ea){var b=new Sk(a);_.Ek(function(){Tk(this,b)},this)}};
Tk=function(a,b){if(0==a.Ea)if(a.$a){var c=a.$a;if(c.Qj){for(var d=0,e=null,f=null,g=c.Qj;g&&(g.rp||(d++,g.ol==a&&(e=g),!(e&&1<d)));g=g.next)e||(f=g);e&&(0==c.Ea&&1==d?Tk(c,b):(f?(d=f,d.next==c.ln&&(c.ln=d),d.next=d.next.next):Uk(c),Vk(c,e,3,b)))}a.$a=null}else a.lh(3,b)};_.Xk=function(a,b){a.Qj||2!=a.Ea&&3!=a.Ea||Wk(a);a.ln?a.ln.next=b:a.Qj=b;a.ln=b};
Rk=function(a,b,c,d){var e=_.Jk(null,null,null);e.ol=new _.Gk(function(f,g){e.xr=b?function(k){try{var l=b.call(d,k);f(l)}catch(m){g(m)}}:f;e.jo=c?function(k){try{var l=c.call(d,k);void 0===l&&k instanceof Sk?g(k):f(l)}catch(m){g(m)}}:g});e.ol.$a=a;_.Xk(a,e);return e.ol};_.Gk.prototype.v1=function(a){this.Ea=0;this.lh(2,a)};_.Gk.prototype.w1=function(a){this.Ea=0;this.lh(3,a)};
_.Gk.prototype.lh=function(a,b){0==this.Ea&&(this===b&&(a=3,b=new TypeError("Promise cannot resolve to itself")),this.Ea=1,Mk(b,this.v1,this.w1,this)||(this.ij=b,this.Ea=a,this.$a=null,Wk(this),3!=a||b instanceof Sk||Yk(this,b)))};
var Mk=function(a,b,c,d){if(a instanceof _.Gk)return _.Xk(a,_.Jk(b||_.cb,c||null,d)),!0;if(_.qk(a))return a.then(b,c,d),!0;if(_.bb(a))try{var e=a.then;if("function"===typeof e)return Zk(a,e,b,c,d),!0}catch(f){return c.call(d,f),!0}return!1},Zk=function(a,b,c,d,e){var f=!1,g=function(l){f||(f=!0,c.call(e,l))},k=function(l){f||(f=!0,d.call(e,l))};try{b.call(a,g,k)}catch(l){k(l)}},Wk=function(a){a.Qz||(a.Qz=!0,_.Ek(a.dT,a))},Uk=function(a){var b=null;a.Qj&&(b=a.Qj,a.Qj=b.next,b.next=null);a.Qj||(a.ln=
null);return b};_.Gk.prototype.dT=function(){for(var a;a=Uk(this);)Vk(this,a,this.Ea,this.ij);this.Qz=!1};var Vk=function(a,b,c,d){if(3==c&&b.jo&&!b.rp)for(;a&&a.Pu;a=a.$a)a.Pu=!1;if(b.ol)b.ol.$a=null,$k(b,c,d);else try{b.rp?b.xr.call(b.context):$k(b,c,d)}catch(e){al.call(null,e)}Ik.put(b)},$k=function(a,b,c){2==b?a.xr.call(a.context,c):a.jo&&a.jo.call(a.context,c)},Yk=function(a,b){a.Pu=!0;_.Ek(function(){a.Pu&&al.call(null,b)})},al=sk,Sk=function(a){_.Vc.call(this,a)};_.K(Sk,_.Vc);
Sk.prototype.name="cancel";var Pk=function(a,b,c){this.promise=a;this.resolve=b;this.reject=c};
